version: '3.3'

networks:
  my_network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
      - ~/pgadmin-data:/var/lib/pgadmin
      - ~/pgadmin-data/servers.json:/pgadmin4/servers.json
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=octaviobruza17@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=octavio44288476
    ports:
      - 5050:80
    networks:
      - my_network
