version: '3.3'

networks:
  my_network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=octaviob17
      - POSTGRES_PASSWORD=octavio44288476
    ports:
      - 5432:5432
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=octaviobruza17@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=octavio44288476
    ports:
      - 5050:80
    networks:
      - my_network
